server:
  port: 9898
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/test
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.baizhi.gjc.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.baizhi.gjc.dao: debug
    com.baizhi.gjc.service: debug